import { supabase } from './supabase';
import type { InstitutionId, MaterialType, StudyMaterial, FeedPost } from '../types';
import type { SupabaseProfileRow } from './profileMapper';

export interface SchoolCourseRow { id: string; code: string; title: string; units: number; level: number; semester: number | null; programme_id: string | null; department_id: string; is_active: boolean; }
export interface ResourceRow { id: string; course_id: string | null; title: string; description: string | null; resource_type: string; file_url: string | null; external_url: string | null; uploaded_by: string | null; status: string; created_at: string; original_filename: string | null; mime_type: string | null; file_size: number | null; storage_path: string | null; }

const INSTITUTIONS: InstitutionId[] = ['UNICAL','UNILAG','UI','ABU','UNN','OAU','FUTO','UNIBEN','LASU','DELSU','ALL'];
const toInstitutionId = (value?: string | null): InstitutionId => value && INSTITUTIONS.includes(value as InstitutionId) ? value as InstitutionId : 'UNICAL';
const toMaterialType = (value?: string | null): MaterialType => value === 'past_question' ? 'past_question' : value === 'lecture_note' ? 'lecture_summary' : value === 'course_outline' ? 'project_guide' : value === 'textbook' ? 'handwritten_note' : 'formula_sheet';
const requireClient = () => { if (!supabase) throw new Error('Supabase is not configured.'); return supabase; };

export async function getMyProfile(userId: string): Promise<SupabaseProfileRow | null> { const { data, error } = await requireClient().from('profiles').select('*, institutions(acronym)').eq('id', userId).maybeSingle(); if (error) throw error; return data as SupabaseProfileRow | null; }
export async function updateMyProfile(userId: string, updates: Partial<Pick<SupabaseProfileRow, 'full_name' | 'school' | 'faculty' | 'department' | 'level' | 'session' | 'matric_number' | 'avatar_url'>>) { const { data, error } = await requireClient().from('profiles').update(updates).eq('id', userId).select('*, institutions(acronym)').single(); if (error) throw error; return data as SupabaseProfileRow; }

export async function getMyCourses(programmeId: string, level: string) { let query = requireClient().from('courses').select('id,code,title,units,level,semester,programme_id,department_id,is_active').eq('programme_id', programmeId).eq('is_active', true).order('level').order('semester').order('code'); const numericLevel = Number.parseInt(level, 10); if (Number.isFinite(numericLevel)) query = query.eq('level', numericLevel); const { data, error } = await query; if (error) throw error; return (data ?? []) as SchoolCourseRow[]; }
export async function getApprovedResourcesForCourses(courseIds: string[]) { if (!courseIds.length) return [] as ResourceRow[]; const { data, error } = await requireClient().from('resources').select('id,course_id,title,description,resource_type,file_url,external_url,uploaded_by,status,created_at,original_filename,mime_type,file_size,storage_path').in('course_id', courseIds).eq('status', 'approved').order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as ResourceRow[]; }
export async function getApprovedPastQuestions(courseIds: string[]) { if (!courseIds.length) return []; const { data, error } = await requireClient().from('past_questions').select('id,course_id,title,year,session,semester,exam_type,file_url,status,created_at').in('course_id', courseIds).eq('status', 'approved').order('year', { ascending: false }); if (error) throw error; return data ?? []; }

export function mapResourceToStudyMaterial(resource: ResourceRow, course?: SchoolCourseRow, institutionId: InstitutionId = 'ALL'): StudyMaterial { const level = course?.level && course.level >= 100 && course.level <= 500 ? `${course.level}L` as StudyMaterial['level'] : 'General'; return { id: resource.id, title: resource.title, courseCode: course?.code ?? 'RESOURCE', courseTitle: course?.title ?? 'Academic Resource', institutionId, department: '', faculty: '', level, semester: course?.semester === 1 ? '1st Semester' : course?.semester === 2 ? '2nd Semester' : 'All Year', materialType: toMaterialType(resource.resource_type), academicSession: '', unlockPrice: 0, uploader: { id: resource.uploaded_by ?? 'unknown', name: 'Verified Contributor', avatar: '', badge: 'Student Contributor', institution: institutionId, rating: 0 }, isVerified: resource.status === 'approved', verificationStatus: 'APPROVED', rating: 0, reviewCount: 0, unlockCount: 0, fileSizeKb: resource.file_size ? Math.round(resource.file_size / 1024) : 0, pageCount: 0, summary: resource.description ?? '', coreConcepts: [], fullTextContent: '', crossCampusEquivalents: [], createdAt: resource.created_at }; }

export async function getMyAcademicMaterials(profile: SupabaseProfileRow): Promise<StudyMaterial[]> { if (!profile.programme_id) return []; const institutionId = toInstitutionId(profile.institutions?.acronym); const courses = await getMyCourses(profile.programme_id, profile.level); const resources = await getApprovedResourcesForCourses(courses.map(c => c.id)); const byId = new Map(courses.map(c => [c.id, c])); return resources.map(resource => mapResourceToStudyMaterial(resource, resource.course_id ? byId.get(resource.course_id) : undefined, institutionId)); }

export async function getCampusFeedPosts(): Promise<FeedPost[]> { const { data, error } = await requireClient().from('campus_posts').select('id,author_id,title,content,category,attachment_path,attachment_name,moderation_status,moderated_price,institution_id,department_id,course_id,created_at,profiles(full_name,level,department,institutions(acronym))').eq('moderation_status', 'APPROVED').order('created_at', { ascending: false }); if (error) throw error; return (data ?? []).map((row: any) => { const p = row.profiles ?? {}; const institution = toInstitutionId(p.institutions?.acronym); return { id: row.id, authorId: row.author_id, authorName: p.full_name ?? 'Student Contributor', authorInstitution: institution, authorDepartment: p.department ?? '', authorLevel: p.level ?? '', title: row.title, content: row.content, category: row.category, attachment: row.attachment_name ? { name: row.attachment_name, fileSize: '', fileType: 'FILE' } : undefined, priceRequested: Number(row.moderated_price ?? 0), moderatedPrice: Number(row.moderated_price ?? 0), moderationStatus: row.moderation_status, likesCount: 0, likedByUserIds: [], comments: [], viewsCount: 0, createdAt: row.created_at } as FeedPost; }); }
