import { useEffect, useState } from 'react';
import { supabase } from '../src/lib/supabase';
import AdminLayout from './AdminLayout';

type QueueRow = { id: string; user_id: string; status: string; form_data: Record<string, unknown>; created_at: string; service_catalog?: { title: string } | null };

export default function AdminQueuePage() {
  const [rows, setRows] = useState<QueueRow[]>([]); const [filter, setFilter] = useState('all');
  async function load() { let query = supabase.from('service_requests').select('id,user_id,status,form_data,created_at,service_catalog(title)').order('created_at', { ascending: false }); if (filter !== 'all') query = query.eq('status', filter); const { data } = await query; setRows((data || []) as QueueRow[]); }
  useEffect(() => { load(); }, [filter]);
  async function updateStatus(id: string, status: string) { await supabase.from('service_requests').update({ status, updated_at: new Date().toISOString() }).eq('id', id); await load(); }
  return <AdminLayout><div className="admin-page"><div className="admin-page-header"><div><h1>Service Processing Queue</h1><p>Process NELFUND, JAMB, result-checking and admission service requests.</p></div><select className="admin-select" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All statuses</option><option value="submitted">Submitted</option><option value="reviewing">Reviewing</option><option value="processing">Processing</option><option value="completed">Completed</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option></select></div><div className="admin-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Student</th><th>Service</th><th>Details</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td className="mono accent">{String(row.form_data?.fullName || row.form_data?.name || row.user_id.slice(0, 8))}</td><td>{row.service_catalog?.title || 'Service request'}</td><td>{String(row.form_data?.message || row.form_data?.requestDetails || '—')}</td><td><span className={`status-badge ${row.status}`}>{row.status}</span></td><td>{new Date(row.created_at).toLocaleString()}</td><td><div className="admin-action-row"><button className="admin-btn small" onClick={() => updateStatus(row.id, 'processing')}>Process</button><button className="admin-btn small success" onClick={() => updateStatus(row.id, 'completed')}>Complete</button><button className="admin-btn small danger" onClick={() => updateStatus(row.id, 'rejected')}>Reject</button></div></td></tr>)}{!rows.length && <tr><td colSpan={6} className="empty-state">No matching service requests.</td></tr>}</tbody></table></div></div></div></AdminLayout>;
}
