import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Bell, BookOpen, BriefcaseBusiness, CheckCircle2, Clock3, FileText, GraduationCap, Home as HomeIcon, LayoutDashboard, Menu, Newspaper, Search, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import { supabase } from './lib/supabase';
import { cbtQuestions, cbtDurationSeconds } from './data/cbtQuestions';
import { serviceWorkflows } from './data/serviceWorkflows';

const services = [
  ['nelfund-loan','NELFUND Loan Assistance','Funding'],
  ['results','WAEC / NECO Result Checking','Results'],
  ['scratch-cards','WAEC / NECO Scratch Cards','Cards'],
  ['jamb-slip','JAMB Exam Slip Printing','JAMB'],
  ['admission-letters','Admission Deferment & Supplementary Letters','Admissions'],
] as const;

const news = [
  { slug:'jamb-update', title:'JAMB update desk', category:'JAMB', text:'A central place for exam notices, slip updates and candidate guidance.', date:'Today' },
  { slug:'admission-watch', title:'Admission watch', category:'Admissions', text:'Track admission lists, supplementary opportunities and application reminders.', date:'Latest' },
  { slug:'funding-alerts', title:'Student funding alerts', category:'Funding', text:'Follow verified funding and student-support information as it is published.', date:'Latest' },
];
const opportunities = [
  { slug:'undergraduate-scholarships', title:'Undergraduate scholarship board', type:'Scholarship', deadline:'Rolling', text:'Scholarship discovery hub for students and fresh graduates.' },
  { slug:'graduate-opportunities', title:'Entry-level opportunities', type:'Jobs', deadline:'Rolling', text:'Starter opportunities for students preparing for life after school.' },
  { slug:'study-abroad', title:'Study-abroad opportunity desk', type:'Study Abroad', deadline:'Varies', text:'Organised listings with requirements and official application links.' },
];
const schools = ['University of Calabar','University of Lagos','University of Nigeria, Nsukka','University of Ibadan','Ahmadu Bello University','Federal Polytechnic'];

function go(path:string){ window.history.pushState({},'',path); window.dispatchEvent(new PopStateEvent('popstate')); }

const navItems = [
  ['/','Home',HomeIcon],['/cbt','CBT Practice',BookOpen],['/services','Services',BriefcaseBusiness],['/news','News',Newspaper],['/opportunities','Opportunities',GraduationCap],['/community','Community',Users],
] as const;

function AppShell({children}:{children:React.ReactNode}){
  const [menu,setMenu]=useState(false);
  const current=window.location.pathname.replace(/\/$/,'')||'/';
  return <div className="app-shell">
    <header className="topbar">
      <div className="brand" onClick={()=>go('/')}><span className="brand-mark">ER</span><span>EduReach <b>Hub</b></span></div>
      <div className="top-search" onClick={()=>go('/search')}><Search size={17}/><span>Search services, CBT, news &amp; opportunities</span></div>
      <div className="top-actions"><button className="icon-btn" aria-label="Notifications"><Bell size={19}/></button><button className="ghost" onClick={()=>go('/dashboard/profile')}>My account</button><button className="primary small" onClick={()=>go('/login')}>Sign in</button></div>
      <button className="menu-btn" onClick={()=>setMenu(!menu)}>{menu?<X size={22}/>:<Menu size={22}/>}</button>
    </header>

    <div className="app-layout">
      <aside className={menu?'side-drawer open':'side-drawer'}>
        <div className="drawer-label">MAIN</div>
        <nav>{navItems.map(([href,label,Icon])=><button className={current===href||current.startsWith(`${href}/`)?'active':''} key={href} onClick={()=>{go(href);setMenu(false)}}><Icon size={18}/><span>{label}</span></button>)}</nav>
        <div className="drawer-label">STUDENT</div>
        <nav>
          <button onClick={()=>{go('/schools');setMenu(false)}}><GraduationCap size={18}/><span>Schools</span></button>
          <button onClick={()=>{go('/groups');setMenu(false)}}><Users size={18}/><span>Study Groups</span></button>
          <button onClick={()=>{go('/dashboard');setMenu(false)}}><LayoutDashboard size={18}/><span>Dashboard</span></button>
        </nav>
        <div className="drawer-spacer" />
        <div className="drawer-card"><ShieldCheck size={18}/><strong>Verified-first</strong><p>Official links and verification states stay visible.</p></div>
      </aside>
      <main className="main-workspace">{children}</main>
    </div>

    <nav className="bottom-nav">{navItems.slice(0,5).map(([href,label,Icon])=><button className={current===href||current.startsWith(`${href}/`)?'active':''} key={href} onClick={()=>go(href)}><Icon size={18}/><span>{label.replace(' Practice','')}</span></button>)}</nav>
    <footer className="footer"><div><div className="brand"><span className="brand-mark">ER</span>EduReach <b>Hub</b></div><p>Student services, CBT practice, education news, opportunities and community in one platform.</p></div><div><strong>Platform</strong><button onClick={()=>go('/about')}>About</button><button onClick={()=>go('/services')}>Services</button><button onClick={()=>go('/dashboard')}>Dashboard</button></div><div><strong>Account</strong><button onClick={()=>go('/login')}>Login</button><button onClick={()=>go('/register')}>Register</button><button onClick={()=>go('/forgot-password')}>Reset password</button></div></footer>
  </div>
}
function Page({title,eyebrow,children,actions}:{title:string;eyebrow?:string;children:React.ReactNode;actions?:React.ReactNode}){return <section className="page"><div className="container"><div className="page-head">{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{actions&&<div className="page-actions">{actions}</div>}</div>{children}</div></section>}
function Card({children,onClick}:{children:React.ReactNode;onClick?:()=>void}){return <div className={onClick?'card clickable':'card'} onClick={onClick}>{children}</div>}
function Widget({title,children,action}:{title:string;children:React.ReactNode;action?:()=>void}){return <Card><div className="widget-head"><h3>{title}</h3>{action&&<button className="link-btn" onClick={action}>View</button>}</div>{children}</Card>}

function Home(){
  const [query,setQuery]=useState('');
  const searchText=query.trim().toLowerCase();
  const filteredServices=useMemo(()=>services.filter(s=>`${s[1]} ${s[2]}`.toLowerCase().includes(searchText)),[searchText]);
  const quickActions: Array<[React.ComponentType<{size?:number}>,string,string,string,string]> = [[BookOpen,'CBT Quick Launch','Timed practice with instant scoring','/cbt','JAMB / WAEC / NECO'],[BriefcaseBusiness,'Digital Services Portal','Apply for a service and track it','/services','5 services'],[Newspaper,'News Timeline','Read current education and campus updates','/news','Updates'],[GraduationCap,'Opportunity Board','Scholarships, jobs and study options','/opportunities','Discovery']];
  return <section className="dashboard-home"><div className="container">
    <div className="dashboard-banner-grid">
      <button className="alert-banner" onClick={()=>go('/news/funding-alerts')}><span className="banner-icon green"><Bell size={16}/></span><span><b>NELFUND desk</b><small>Funding updates and application guidance</small></span></button>
      <button className="alert-banner" onClick={()=>go('/cbt')}><span className="banner-icon blue"><BookOpen size={16}/></span><span><b>CBT engine</b><small>Launch timed JAMB, WAEC and NECO practice</small></span></button>
      <button className="alert-banner" onClick={()=>go('/opportunities')}><span className="banner-icon purple"><Sparkles size={16}/></span><span><b>Opportunity board</b><small>Scholarships, jobs and study opportunities</small></span></button>
    </div>

    <div className="workspace-grid">
      <div className="workspace-main">
        <section className="workspace-intro"><div><span className="eyebrow">STUDENT WORKSPACE</span><h1>Good to see you on EduReach Hub.</h1><p>Handle the student task in front of you first. Everything else stays organised around it.</p></div><button className="secondary" onClick={()=>go('/dashboard')}><LayoutDashboard size={16}/> Open dashboard</button></section>
        <section className="section-card"><div className="section-head compact"><div><span className="eyebrow">QUICK ACTIONS</span><h2>Start with what you need</h2></div></div><div className="utility-grid">{quickActions.map(([Icon,t,d,p,tag])=><div className="utility-card" key={t}><div className="utility-top"><span className="utility-icon"><Icon size={19}/></span><span className="badge">{tag}</span></div><div><h3>{t}</h3><p>{d}</p></div><div className="utility-footer"><button className="primary full" onClick={()=>go(p)}>Open <ArrowRight size={15}/></button></div></div>)}</div></section>
        <section className="section-card"><div className="section-head compact"><div><span className="eyebrow">SERVICE SHORTCUTS</span><h2>Five student services</h2></div><button className="link-btn" onClick={()=>go('/services')}>All services <ArrowRight size={15}/></button></div><div className="mini-service-grid">{services.map(([id,title,group])=><Card key={id} onClick={()=>go('/services/'+id)}><div className="row-between"><span className="utility-icon small-icon"><FileText size={17}/></span><span className="badge">{group}</span></div><h3>{title}</h3><p>Start a guided request.</p></Card>)}</div></section>
        <section className="section-card"><div className="section-head compact"><div><span className="eyebrow">NEWS TIMELINE</span><h2>Latest education updates</h2></div><button className="link-btn" onClick={()=>go('/news')}>View all <ArrowRight size={15}/></button></div><div className="timeline-list">{news.map(n=><Card key={n.slug} onClick={()=>go('/news/'+n.slug)}><div className="timeline-thumb"><span className="badge">{n.category}</span></div><div><div className="row-between"><small>{n.date}</small><ArrowRight size={15}/></div><h3>{n.title}</h3><p>{n.text}</p></div></Card>)}</div></section>
      </div>
      <aside className="context-sidebar">
        <Widget title="Deadline tracker" action={()=>go('/dashboard')}><div className="deadline"><span className="deadline-date">SOON</span><div><b>Check your outstanding student tasks</b><p>Open your dashboard for service requests, exams and personal deadlines.</p></div></div><button className="secondary full" onClick={()=>go('/dashboard')}>Open tracker</button></Widget>
        <Widget title="CBT weekly leaderboard" action={()=>go('/cbt')}><div className="leader"><span>#1</span><div><b>Practice leaderboard</b><p>Complete a CBT session to start appearing here.</p></div></div><button className="primary full" onClick={()=>go('/cbt')}>Practice now</button></Widget>
        <Widget title="Quick Q&A" action={()=>go('/community')}><div className="qa-item"><span className="badge alt">Community</span><b>Ask a question about your course or school.</b><p>Get student-to-student answers in the community desk.</p></div><button className="secondary full" onClick={()=>go('/community')}>Open Q&amp;A</button></Widget>
        <Widget title="Global search"><div className="search-widget"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search EduReach..."/></div>{query&&<div className="search-suggestions">{filteredServices.slice(0,4).map(s=><button key={s[0]} onClick={()=>go('/services/'+s[0])}>{s[1]} <ArrowRight size={14}/></button>)}</div>}</Widget>
      </aside>
    </div>
  </div></section>;
}

function About(){return <Page title="About EduReach Hub" eyebrow="PLATFORM"><div className="two-col"><Card><h3>Built around student actions</h3><p>EduReach is designed as a practical student platform rather than a brochure site. The core product areas are CBT practice, digital services, education information, opportunities and community.</p></Card><Card><h3>Trust and verification</h3><p>Official links, verification states and clear source labels are part of the product architecture so students can tell the difference between guidance and verified announcements.</p></Card></div><div className="section-inner"><h2>The platform zones</h2><div className="four-grid">{['Public Gateway','CBT & Practice','Services / News / Opportunities / Community','Student & Admin Portals'].map(x=><Card key={x}><h3>{x}</h3><p>Focused navigation and functionality for this product zone.</p></Card>)}</div></div></Page>}
function SearchPage(){const [q,setQ]=useState('');const all=[...services.map(x=>({type:'Service',title:x[1],path:'/services/'+x[0]})),...news.map(x=>({type:'News',title:x.title,path:'/news/'+x.slug})),...opportunities.map(x=>({type:x.type,title:x.title,path:'/opportunities/'+x.slug})),...cbtQuestions.map(x=>({type:'CBT',title:x.question,path:'/cbt'}))];const results=all.filter(x=>x.title.toLowerCase().includes(q.toLowerCase())).slice(0,30);return <Page title="Global Search" eyebrow="SEARCH"><div className="search-large"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search subjects, services, news, schools or opportunities..." autoFocus/></div><div className="results-grid">{(q?results:all.slice(0,10)).map((r,i)=><Card key={r.type+r.title+i} onClick={()=>go(r.path)}><span className="badge">{r.type}</span><h3>{r.title}</h3><span className="card-link">Open result <ArrowRight size={15}/></span></Card>)}</div></Page>}
function AuthPage({mode}:{mode:'login'|'register'|'forgot'}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [phone,setPhone]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');try{if(mode==='forgot'){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/dashboard/profile'});if(error)throw error;setMessage('Password reset instructions have been sent.')}else if(phone){const {error}=await supabase.auth.signInWithOtp({phone,options:{shouldCreateUser:mode==='register'}});if(error)throw error;setMessage('Check your phone for the verification code.')}else if(mode==='register'){const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw error;setMessage('Account created. Check your email if verification is enabled.')}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;go('/dashboard');window.location.reload()}}catch(err){setMessage(err instanceof Error?err.message:'Something went wrong.')}finally{setBusy(false)}};return <Page title={mode==='forgot'?'Reset your password':mode==='register'?'Create your account':'Welcome back'} eyebrow="ACCOUNT"><div className="auth-card"><form onSubmit={submit}>{mode==='register'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" required/>}<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email address" required={!phone}/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number (optional)"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password" required={mode!=='forgot'&&!phone}/><button className="primary full" disabled={busy}>{busy?'Please wait...':mode==='forgot'?'Send reset link':mode==='register'?'Create account':'Sign in'}</button>{mode!=='forgot'&&<button type="button" className="secondary full" onClick={()=>supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin+'/dashboard'}})}>Continue with Google</button>}{message&&<div className="notice">{message}</div>}</form><div className="auth-links">{mode!=='login'&&<button onClick={()=>go('/login')}>Sign in</button>}{mode!=='register'&&<button onClick={()=>go('/register')}>Create account</button>}{mode!=='forgot'&&<button onClick={()=>go('/forgot-password')}>Forgot password?</button>}</div></div></Page>}
function Services(){return <Page title="Digital Services Center" eyebrow="SERVICES" actions={<button className="secondary" onClick={()=>go('/services/track')}>Track request</button>}><div className="results-grid">{services.map(([id,title,group])=><Card key={id} onClick={()=>go('/services/'+id)}><div className="row-between"><span className="utility-icon small-icon"><FileText size={17}/></span><span className="badge">{group}</span></div><h3>{title}</h3><p>Start a request, see the required information and track your submission.</p><span className="card-link">Open service <ArrowRight size={15}/></span></Card>)}</div></Page>}
function ServicePage({slug}:{slug:string}){const workflow=serviceWorkflows[slug];const service=services.find(s=>s[0]===slug);const [form,setForm]=useState<Record<string,string>>({});const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);if(!workflow||!service)return <NotFound/>;const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');const {data:{user}}=await supabase.auth.getUser();if(!user){go('/login');return}try{const {data:cat}=await supabase.from('service_catalog').select('id').eq('service_key',slug).single();if(!cat)throw new Error('Service is not configured in the database yet.');const {data,error}=await supabase.from('service_requests').insert({user_id:user.id,service_id:cat.id,form_data:form}).select('id').single();if(error)throw error;setMessage('Request submitted. Reference: '+data.id);setForm({})}catch(err){setMessage(err instanceof Error?err.message:'Request failed.')}finally{setBusy(false)}};return <Page title={service[1]} eyebrow="SERVICE"><div className="two-col"><div><Card><h3>What this service does</h3><p>{workflow.overview}</p></Card><Card><h3>How it works</h3><ol className="steps">{workflow.steps.map(s=><li key={s}>{s}</li>)}</ol></Card><div className="two-col compact">{[ ['Requirements',workflow.requirements],['Important notes',workflow.notes] ].map(([t,items])=><Card key={t as string}><h3>{t as string}</h3><ul>{(items as string[]).map(i=><li key={i}>{i}</li>)}</ul></Card>)}</div></div><Card><h3>Start request</h3><p className="muted-text">You must be signed in to submit a request.</p><form onSubmit={submit}>{workflow.fields.map(f=>f.type==='textarea'?<textarea key={f.name} required={f.required} value={form[f.name]||''} onChange={e=>setForm({...form,[f.name]:e.target.value})} placeholder={f.placeholder}/>:f.type==='select'?<select key={f.name} required={f.required} value={form[f.name]||''} onChange={e=>setForm({...form,[f.name]:e.target.value})}><option value="">{f.label}</option>{f.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input key={f.name} required={f.required} type={f.type||'text'} value={form[f.name]||''} onChange={e=>setForm({...form,[f.name]:e.target.value})} placeholder={f.placeholder||f.label}/>) }<button className="primary full" disabled={busy}>{busy?'Submitting...':'Submit request'}</button>{message&&<div className="notice">{message}</div>}</form></Card></div></Page>}
function ServiceTrack(){const [ref,setRef]=useState('');const [phone,setPhone]=useState('');const [result,setResult]=useState<any>(null);const [message,setMessage]=useState('');const search=async(e:React.FormEvent)=>{e.preventDefault();setMessage('');const {data:{user}}=await supabase.auth.getUser();if(!user){setMessage('Sign in first so EduReach can securely show your requests.');return}const {data,error}=await supabase.from('service_requests').select('id,status,created_at,form_data,service_catalog(title)').eq('user_id',user.id).order('created_at',{ascending:false}).limit(20);if(error) setMessage(error.message);else{const found=data?.find((r:any)=>!ref||r.id===ref||(phone&&r.form_data?.whatsapp===phone));setResult(found||null);if(!found)setMessage('No matching request found. Use your full reference or the WhatsApp number used in the request.')}};return <Page title="Application Tracking" eyebrow="SERVICES"><div className="auth-card"><form onSubmit={search}><input value={ref} onChange={e=>setRef(e.target.value)} placeholder="Reference code"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="WhatsApp number"/><button className="primary full">Track request</button></form>{result&&<div className="track-result"><span className="badge">{result.status}</span><h3>{result.service_catalog?.title}</h3><p>Reference: {result.id}</p><p>Submitted: {new Date(result.created_at).toLocaleString()}</p></div>}{message&&<div className="notice">{message}</div>}</div></Page>}
function News(){return <Page title="News & Real-Time Campus Updates" eyebrow="NEWS"><div className="filters"><input placeholder="Search news..."/></div><div className="results-grid">{news.map(n=><Card key={n.slug} onClick={()=>go('/news/'+n.slug)}><span className="badge">{n.category}</span><h3>{n.title}</h3><p>{n.text}</p><span className="card-link">Read <ArrowRight size={15}/></span></Card>)}</div></Page>}
function NewsDetail({slug}:{slug:string}){const item=news.find(n=>n.slug===slug);if(!item)return <NotFound/>;return <Page title={item.title} eyebrow={item.category}><Card><p>{item.text}</p><h3>EduReach editorial desk</h3><p>This detail page is ready for verified editorial content, source tags, sharing and community discussion.</p><button className="secondary" onClick={()=>go('/community')}>Discuss this update</button></Card></Page>}
function Opportunities({slug}:{slug?:string}){if(slug){const item=opportunities.find(o=>o.slug===slug);if(!item)return <NotFound/>;return <Page title={item.title} eyebrow={item.type}><Card><span className="badge">{item.type}</span><h3>{item.deadline}</h3><p>{item.text}</p><h4>Application checklist</h4><ul><li>Read eligibility requirements</li><li>Prepare required documents</li><li>Use the official application link</li></ul></Card></Page>}return <Page title="Jobs & Scholarship Directory" eyebrow="OPPORTUNITIES"><div className="results-grid">{opportunities.map(o=><Card key={o.slug} onClick={()=>go('/opportunities/'+o.slug)}><span className="badge alt">{o.type}</span><h3>{o.title}</h3><p>{o.text}</p><span className="card-link">View opportunity <ArrowRight size={15}/></span></Card>)}</div></Page>}
function Schools(){return <Page title="School Directory" eyebrow="SCHOOLS"><div className="results-grid">{schools.map(s=><Card key={s}><SchoolRow name={s}/></Card>)}</div></Page>}
function SchoolRow({name}:{name:string}){return <><div className="row-between"><GraduationCap size={22}/><span className="badge">Institution</span></div><h3>{name}</h3><p>School profile, admission notices, fees and student updates will live here.</p></>}
function Community(){return <Page title="Community Forum & Q&A" eyebrow="COMMUNITY"><div className="two-col"><Card><h3>Ask a question</h3><p>Post academic questions, compare answers and build a searchable knowledge base.</p><button className="primary" onClick={()=>{document.getElementById('question')?.focus()}}>Post question</button></Card><Card><h3>Popular topics</h3><ul><li>Coursework & examinations</li><li>Admissions</li><li>School rules</li><li>Student life</li></ul></Card></div><div className="section-inner" id="question"><Card><textarea placeholder="What do you want the community to help with?"/><button className="primary">Publish question</button></Card></div></Page>}
function Groups(){return <Page title="Study Groups" eyebrow="COMMUNITY"><div className="results-grid">{['EEE 300 Level Study Circle','JAMB Mathematics Drill','WAEC Result Support','Engineering Project Group','Admission Applicants Circle','Campus Opportunities Group'].map(x=><Card key={x}><Users size={22}/><h3>{x}</h3><p>Join a focused study circle and coordinate sessions or WhatsApp discussions.</p><button className="secondary">Join group</button></Card>)}</div></Page>}
function Dashboard(){const [user,setUser]=useState<any>(null);const [requests,setRequests]=useState<any[]>([]);useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user));},[]);useEffect(()=>{if(user)supabase.from('service_requests').select('id,status,created_at,service_catalog(title)').eq('user_id',user.id).order('created_at',{ascending:false}).limit(5).then(({data})=>setRequests(data||[]));},[user]);if(!user)return <Page title="Student Dashboard" eyebrow="PORTAL"><Card><h3>Sign in to open your dashboard</h3><button className="primary" onClick={()=>go('/login')}>Sign in</button></Card></Page>;return <Page title="Student Dashboard" eyebrow="PORTAL"><div className="stat-grid"><Card><strong>{requests.length}</strong><span>Recent service requests</span></Card><Card><strong>0</strong><span>Saved opportunities</span></Card><Card><strong>0</strong><span>Practice sessions</span></Card><Card><strong>—</strong><span>Performance score</span></Card></div><div className="section-inner"><div className="section-head"><h2>Recent requests</h2><button className="link-btn" onClick={()=>go('/dashboard/orders')}>Full history</button></div>{requests.map(r=><Card key={r.id}><div className="row-between"><span>{r.service_catalog?.title}</span><span className="badge">{r.status}</span></div><small>{r.id}</small></Card>)}</div></Page>}
function Orders(){return <DashboardSub title="Orders & Transactions"><p>Every digital-service request, payment reference and transaction record will appear here. Current service submissions are pulled from the secure service-request ledger.</p></DashboardSub>}
function Profile(){const [user,setUser]=useState<any>(null);const [name,setName]=useState('');const [message,setMessage]=useState('');useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user);setName(data.user?.user_metadata?.full_name||'')});},[]);const save=async(e:React.FormEvent)=>{e.preventDefault();const {error}=await supabase.auth.updateUser({data:{full_name:name}});setMessage(error?error.message:'Profile updated.');};return <DashboardSub title="Profile Settings"><form className="auth-card" onSubmit={save}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" required/><input value={user?.email||''} disabled placeholder="Email"/><input placeholder="Target institution"/><input placeholder="State of origin"/><input placeholder="Phone number"/><button className="primary full">Save profile</button>{message&&<div className="notice">{message}</div>}</form></DashboardSub>}
function DashboardSub({title,children}:{title:string;children:React.ReactNode}){return <Page title={title} eyebrow="PORTAL"><div className="narrow">{children}</div></Page>}
function Admin(){return <Page title="Master Admin Dashboard" eyebrow="BACKOFFICE"><div className="stat-grid">{[['Users','Manage registrations'],['CBT bank','Manage questions and subjects'],['Service requests','Process applications'],['Editorial','Publish news and opportunities'],['Transactions','Track payments'],['Analytics','Monitor conversion and completion']].map(([a,b])=><Card key={a}><strong>{a}</strong><p>{b}</p><button className="secondary">Open</button></Card>)}</div></Page>}
function CbtLobby(){return <Page title="CBT & Practice Engine" eyebrow="CBT"><div className="results-grid">{['JAMB','WAEC','NECO','Post-UTME'].map(x=><Card key={x} onClick={()=>go('/cbt/'+x.toLowerCase())}><BookOpen size={22}/><h3>{x}</h3><p>Choose subjects, practice mode and time limit.</p><span className="card-link">Start <ArrowRight size={15}/></span></Card>)}</div></Page>}
function CbtSelect({exam}:{exam:string}){const subjects=[...new Set(cbtQuestions.map(q=>q.subject))];return <Page title={`${exam.toUpperCase()} Practice`} eyebrow="CBT"><div className="two-col"><Card><h3>Choose subjects</h3>{subjects.map(s=><label className="checkrow" key={s}><input type="checkbox" defaultChecked/> {s}</label>)}</Card><Card><h3>Practice mode</h3><select defaultValue="study"><option value="study">Study Mode</option><option value="timed">Timed Exam</option></select><button className="primary full" onClick={()=>go('/cbt/session/demo')}>Start test</button></Card></div></Page>}
function CbtSession({id}:{id:string}){const [i,setI]=useState(0);const [answers,setAnswers]=useState<Record<string,number>>({});const [left,setLeft]=useState(cbtDurationSeconds);const q=cbtQuestions[i%cbtQuestions.length];useEffect(()=>{const t=setInterval(()=>setLeft(s=>Math.max(0,s-1)),1000);return()=>clearInterval(t)},[]);useEffect(()=>{if(left===0)finish()},[left]);function finish(){const score=cbtQuestions.reduce((n,x)=>n+(answers[x.id]===x.answer?1:0),0);localStorage.setItem('edurecah-cbt-result',JSON.stringify({score,total:cbtQuestions.length,answers}));go('/cbt/result/'+id);window.location.reload()}return <Page title="Active CBT Session" eyebrow="EXAM"><div className="exam-layout"><div className="exam-card"><div className="row-between"><span>Question {i+1} / {cbtQuestions.length}</span><span className="timer"><Clock3 size={16}/>{String(Math.floor(left/60)).padStart(2,'0')}:{String(left%60).padStart(2,'0')}</span></div><h2>{q.question}</h2>{q.options.map((o,n)=><button key={o} className={answers[q.id]===n?'option selected':'option'} onClick={()=>setAnswers({...answers,[q.id]:n})}>{String.fromCharCode(65+n)}. {o}</button>)}<div className="exam-footer"><button className="secondary" disabled={i===0} onClick={()=>setI(i-1)}>Previous</button>{i===cbtQuestions.length-1?<button className="primary" onClick={finish}>Submit test</button>:<button className="primary" onClick={()=>setI(i+1)}>Next</button>}</div></div><div className="exam-nav">{cbtQuestions.map((x,n)=><button key={x.id} className={answers[x.id]!==undefined?'done':''} onClick={()=>setI(n)}>{n+1}</button>)}</div></div></Page>}
function CbtResult(){const result=JSON.parse(localStorage.getItem('edurecah-cbt-result')||'{}');const score=result.score||0;const total=result.total||cbtQuestions.length;return <Page title="Performance & Score Analytics" eyebrow="CBT"><div className="result-hero"><div><span className="eyebrow">LATEST RESULT</span><strong>{score}/{total}</strong><p>{Math.round((score/total)*100)}% score</p></div><button className="primary" onClick={()=>go('/cbt')}>Practice again</button></div><div className="results-grid">{cbtQuestions.slice(0,6).map(q=><Card key={q.id}><span className="badge">{q.subject}</span><h3>{q.question}</h3><p>{result.answers?.[q.id]===q.answer?'Correct':'Review this question'}</p></Card>)}</div></Page>}
function NotFound(){return <Page title="Page not found" eyebrow="404"><Card><p>The page you requested does not exist in the EduReach Hub architecture.</p><button className="primary" onClick={()=>go('/')}>Back home</button></Card></Page>}

export default function App(){const [,render]=useState(0);useEffect(()=>{const f=()=>render(x=>x+1);window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)},[]);const path=window.location.pathname.replace(/\/$/,'')||'/';let page:React.ReactNode=path==='/'?<Home/>:path==='/search'?<SearchPage/>:path==='/about'?<About/>:path==='/login'?<AuthPage mode="login"/>:path==='/register'?<AuthPage mode="register"/>:path==='/forgot-password'?<AuthPage mode="forgot"/>:path==='/cbt'?<CbtLobby/>:path.startsWith('/cbt/session/')?<CbtSession id={path.split('/').pop()||'demo'}/>:path.startsWith('/cbt/result/')?<CbtResult/>:path.startsWith('/cbt/')?<CbtSelect exam={decodeURIComponent(path.slice('/cbt/'.length))}/>:path==='/services'?<Services/>:path==='/services/track'?<ServiceTrack/>:path.startsWith('/services/')?<ServicePage slug={decodeURIComponent(path.slice('/services/'.length))}/>:path==='/news'?<News/>:path.startsWith('/news/')?<NewsDetail slug={decodeURIComponent(path.slice('/news/'.length))}/>:path==='/schools'?<Schools/>:path==='/opportunities'?<Opportunities/>:path.startsWith('/opportunities/')?<Opportunities slug={decodeURIComponent(path.slice('/opportunities/'.length))}/>:path==='/community'?<Community/>:path==='/groups'?<Groups/>:path==='/dashboard'?<Dashboard/>:path==='/dashboard/orders'?<Orders/>:path==='/dashboard/profile'?<Profile/>:path==='/admin'?<Admin/>:<NotFound/>;return <AppShell>{page}</AppShell>}
